---

zk_user: "{{ zk }}"
zk_group: "{{ zk }}"

zk_prefix: ''

zk_source_path: "{{ zk_prefix }}/usr/share/zookeeper"

zk_tree:
  vlb: "{{ zk_prefix }}/var/lib/{{ zk }}"
  log: "{{ zk_prefix }}/var/log/{{ zk }}"
  run: "{{ zk_prefix }}/var/run/{{ zk }}"
  etc: "{{ zk_prefix }}/etc/{{ zk }}"
  bin: "{{ zk_prefix }}/usr/bin"
  lib: "{{ zk_prefix }}/usr/lib/{{ zk }}"

bigtop_version: 0.6.0
bigtop_utils_prefix: /usr/lib/bigtop-utils

# don't need run for deb?
zk_owned_dirs:
  - "{{ zk_tree.vlb }}"
  - "{{ zk_tree.log }}"
  - "{{ zk_tree.run }}"


zk_java_package: "{{ zk }}-{{ zk_version }}.tar.gz"
bigtop_package: "bigtop-{{ bigtop_version }}-project.tar.gz"
