---

- name: zookeeper-service
  command: service {{ zk_service }} status
  ignore_errors: yes
  register: zookeeper_service_status
  notify:
    - initialize zookeeper-service
    - restart zookeeper-service

# Because sudo doesn't work for my development platform
# so the permissions are screwy
- name: initialize zookeeper-service
  shell: service {{ zk_service }} init; chown -R {{ zk_user }}:{{ zk_group }} {{ zk_tree.vlb }}
  ignore_errors: yes
  when: zookeeper_service_status|failed
  notify:
    - zookeeper-service id file
    - start zookeeper-service

- name: zookeeper-service id file
  template: src=myid.j2 dest={{ zk_tree.vlb }}/myid
    mode=0644 owner={{ zk_user }} group={{ zk_group }} backup=no
  notify: start zookeeper-service
  
- name: start zookeeper-service
  service: name={{ zk_service }} state=started enabled=yes
  notify: check zookeeper-service status
  
- name: restart zookeeper-service
  service: name={{ zk_service }} state=restarted
  when: zookeeper_service_status|success
  notify: check zookeeper-service status

- name: check zookeeper-service status
  command: service {{ zk_service }} status
