# parameters:
#   pkg_name
#   pkg_version
#   file
#   dest_dir
#   relative_url
#   symlink

- name: query apache mirrors
  action: get_url url=http://www.apache.org/dyn/closer.cgi
    dest=/tmp/apache_mirror.html thirsty=yes
      
- name: scrape apache mirror url
  action: shell sed -nr 's%^\s*<p><a href="(.+)"><strong>.+</strong></a>\s*</p>$%\\1%p'
    /tmp/apache_mirror.html | tr -d '\n'
  register: apache_mirror
    
- name: create destination directory for apache package
  action: file path=${dest_dir} state=directory mode=0755
    
- name: download package from apache mirror
  action: get_url url=${apache_mirror.stdout}/${relative_url}/${file}
    dest=${dest_dir}/${file} thirsty=no
     
- name: fix permissions on package
  action: file name=${dest_dir}/${file} mode=0644
    
- name: extract package
  action: shell chdir=${dest_dir} creates=${dest_dir}/${pkg_name}-${pkg_version}
    tar xzf ${file}
  only_if: "'${file}'.endswith('.tar.gz')"
      
- name: symbolic link package without version
  action: shell chdir=${dest_dir} creates=${dest_dir}/${pkg_name}
    ln -s ${pkg_name}-${pkg_version} ${pkg_name}
  when_set: ${symlink}
      