
---

- name: publish ZooKeeper artifacts
  hosts: zookeeper_devel
  sudo: False
  vars:
    - zk_build_path: ${zk_source_path}/build
    - zk_release_artifacts:
        - ${zk}-${zk_version}.tar.gz
    - zk_client_c_artifacts:
        - ${zk}-${zk_version}-lib-i686.tar.gz
        - ${zk}-${zk_version}-lib-x86_64.tar.gz
    - zk_client_python_artifacts:
        - contrib/zkpython/dist/ZooKeeper-0.4.linux-i686.tar.gz
        - contrib/zkpython/dist/ZooKeeper-0.4.linux-x86_64.tar.gz
  vars_files:
    - [../vars/devel_site.yml, ../vars/devel.yml]
  tasks:
  
    - include: 
        > 
          ../../common/tasks/rsync.yml
          source_path=${zk_source_path}/build files=${zk_release_artifacts}
          dest_user=${zk_publish_user} dest_host=${zk_publish_host} dest_path=${zk_publish_path}

    - include: 
        > 
          ../../common/tasks/rsync.yml
          source_path=${zk_source_path}/build files=${zk_client_c_artifacts}
          dest_user=${zk_publish_user} dest_host=${zk_publish_host} dest_path=${zk_publish_path}
      when_boolean: $zk_build_client_c

    - include: 
        > 
          ../../common/tasks/rsync.yml
          source_path=${zk_source_path}/build files=${zk_client_python_artifacts}
          dest_user=${zk_publish_user} dest_host=${zk_publish_host} dest_path=${zk_publish_path}
      when_boolean: $zk_build_client_python
      