# parameters:
#   user
#   group
#   pkg_name
#   pkg_version
#   file
#   source_dir
#   dest_dir
#   relative_url

---

  - name: query apache mirrors
    action: get_url url=http://www.apache.org/dyn/closer.cgi
      dest=/tmp/apache_mirror.html thirsty=yes
        
  - name: scrape apache mirror url
    action: shell sed -nr 's%^\s*<p><a href="(.+)"><strong>.+</strong></a>\s*</p>$%\\1%p'
      /tmp/apache_mirror.html | tr -d '\n'
    register: apache_mirror
      
  - include: 
      > 
        ../../common/tasks/fetch.yml
        source_url=${apache_mirror.stdout}/${relative_url}

  - include: 
      > 
        ../../common/tasks/extract.yml
        dir=${dest_dir} extracted=${pkg_name}-${pkg_version} symlink=${pkg_name}
      