# parameters:
#   dest_dir
#   file
#   user
#   group
#   source_dir or source_url

---

  - name: create destination directory ${dest_dir}
    action: file path=${dest_dir} state=directory mode=0755
      owner=${user} group=${group}

  - name: check for filesystem source ${source_dir}
    action: "shell if [ -f ${source_dir}/${file} ]; then rsync -q ${source_dir}/${file} ${dest_dir}; fi"
    when_set: ${source_dir}
  
  - name: check for http source ${source_url}
    action: get_url url=${source_url}/${file} dest=${dest_dir}/${file} thirsty=no
    when_set: ${source_url}
 
  - name: fix permissions
    action: file name=${dest_dir}/${file} mode=0644 owner=${user} group=${group}
