# parameters:
#   packages: distribution: []

---
  - action: apt pkg=${item} state=present
    with_items: ${packages.Ubuntu}
    when_string: ${ansible_distribution} == 'Ubuntu'
  
  - action: yum name=${item} state=present
    with_items: ${packages.Fedora}
    when_string: ${ansible_distribution} == 'Fedora'
