---

- name: configure zookeeper servers
  hosts: zookeeper_server
  sudo: True
  vars_files:
    - ../vars/deploy.yml
    - ["../vars/deploy_${ansible_distribution}.yml",]
    - "../vars/configure.yml"
  tasks:
  
    - name: create zookeeper config file
      action: template src=../templates/zoo.cfg.j2 dest=${zk_tree.etc}/conf/zoo.cfg 
        mode=0644 owner=${zk_user} group=${zk_group} backup=yes
      notify: restart zookeeper-server
    
    - name: create zookeeper server id file
      action: template src=../templates/myid.j2 dest=${zk_tree.vlb}/myid
        mode=0644 owner=${zk_user} group=${zk_group} backup=yes
      notify: restart zookeeper-server
  
    - name: create zookeeper java environment
      action: template src=../templates/java.env.j2 dest=${zk_tree.etc}/conf/java.env
        mode=0644 owner=${zk_user} group=${zk_group} backup=yes
      notify: restart zookeeper-server
      
  handlers:
    - name: restart zookeeper-server
      action: service name=${zk_service} state=restarted
      notify: check service status

    - name: check service status
      action: shell service ${zk_service} status
