---

- name: Format and mount ZooKeeper server data log device
  hosts: zookeeper_server
  sudo: True
  vars_files:
    - ../vars/deploy.yml
    - ["../vars/deploy_${ansible_distribution}.yml",]
  tasks:
    - name: create zookeeper data log mount point
      action: file path=${zk_tree.vlb}/datalog state=directory mode=0755 
        owner=${zk_user} group=${zk_group}
      when_set: ${zk_datalog_device}
      
    - name: mount zookeeper data log device
      action: script ../files/zk_mount_log_device.py -v ${zk_tree.vlb}/datalog
      when_set: ${zk_datalog_device}
      
- name: install ZooKeeper server service from distributions
  hosts: zookeeper_server
  sudo: True
  vars_files:
    - ../vars/deploy.yml
    - ["../vars/deploy_${ansible_distribution}.yml",]
  tasks:
    - name: install supporting packages
      action: yum name=$item state=present
      with_items: [initscripts, "redhat-lsb"]
      only_if: "${zk_install_service} and '${ansible_distribution}' == 'Fedora'"
      
    - name: install ${zk_service} init script
      action: shell install -o root -g root -m 0755 -C
        ${zk_source_path}/bigtop/bigtop-packages/src/${zk_init_script}
        /${zk_prefix}/${initd_dir}/${zk_service}
      only_if: "${zk_install_service}"
      
    - name: install ${zk_service}
      action: shell ${chkconfig_cmd} ${chkconfig_opts} ${zk_service} ${chkconfig_args}
      only_if: "${zk_install_service}"
    
- name: start zookeeper service
  hosts: zookeeper_server
  sudo: True
  vars_files:
    - ../vars/deploy.yml
    - ["../vars/deploy_${ansible_distribution}.yml",]
  tasks:
# this isn't working for some reason?
#    - name: start zookeeper service
#      action: service name=${zk_service} state=started enabled=yes
#      only_if: "${zk_install_service}"
    - name: start zookeeper service
      action: shell service ${zk_service} start
      only_if: "${zk_install_service}"

    - action: shell service ${zk_service} status
      
- include: configure_server.yml
      
