# So, I've built two different zkpython packages
# one uses /usr/lib/python2.7/site-packages/
# the other uses /usr/local/lib/python2.7/dist-packages/
# this probably has to do with the distribution I built on?
# So, I'm just gonna grep the package to see which it is...
# ...and hope it doesn't matter...

---

- name: install zkpython
  hosts: zookeeper_client
  sudo: True
  vars:
    pkg_name: ZooKeeper-0.4.linux-${ansible_machine}.tar.gz 
    pkg_lib: zookeeper.so
  vars_files:
    - ../vars/deploy.yml
    - ["../vars/deploy_${ansible_distribution}.yml",]
  tasks:
    - include: 
        > 
          ../../common/tasks/fetch.yml
          file=${pkg_name}
          user=${zk_user} group=${zk_group} source_dir=${dist_dir} 
          dest_dir=${zk_source_path}
    
    - action: shell chdir=${zk_source_path}
        tar tzf ${pkg_name} | grep -E 'packages/$' | sed 's/.//'
      register: lib_path
    
    - include: 
        > 
          ../../common/tasks/extract.yml
          file=${pkg_name}
          extracted=${lib_path.stdout}/${pkg_lib}
          user=${zk_user} group=${zk_group}
          dir=${zk_source_path}
          
    - action: shell
        install -m 755 -t ${python_libdir} ${zk_source_path}/${lib_path.stdout}/*
