---

- include: init_datalog.yml
  when: zk_datalog_device is defined

- name: install service packages
  yum: name={{ item }} state=present
  with_items: [initscripts, "redhat-lsb"]
  when: ansible_os_family == 'RedHat'
  
- name: install {{ zk_service }} init script
  shell: creates={{ zk_prefix }}/{{ initd_dir }}/{{ zk_service }}
    install -o root -g root -m 0755 -C
    {{ zk_release_path }}/bigtop/bigtop-packages/src/{{ zk_init_script }}
    {{ zk_prefix }}/{{ initd_dir }}/{{ zk_service }}
  notify:  load zookeeper-service
