
---

# So, I've built two different zkpython packages
# one uses /usr/lib/python2.7/site-packages/
# the other uses /usr/local/lib/python2.7/dist-packages/
# this probably has to do with the distribution I built on?
# So, I'm just gonna grep the package to see which it is...
# ...and hope it doesn't matter...
- shell: chdir={{ zk_source_path }}
    tar tzf {{ zk_client_python_package }} | grep -E 'packages/$' | sed 's/.//'
  register: lib_path
    
- include: ../../common/tasks/extract.yml
      file={{ zk_client_python_package }}
      expected={{ lib_path.stdout }}/zookeeper.so
      user={{ zk_user }} 
      group={{ zk_group }}
      dir={{ zk_source_path }}
      
- shell: install -m 755 -C -t {{ python_libdir }} 
    {{ zk_source_path }}/{{ lib_path.stdout }}/*
