---

zk: zookeeper
zk_user: ${zk}
zk_group: ${zk}

zk_prefix: ''

zk_source_path: ${zk_prefix}/usr/share/zookeeper

zk_tree:
  vlb: ${zk_prefix}/var/lib/${zk}
  log: ${zk_prefix}/var/log/${zk}
  run: ${zk_prefix}/var/run/${zk}
  etc: ${zk_prefix}/etc/${zk}
  bin: ${zk_prefix}/usr/bin
  lib: ${zk_prefix}/usr/lib/${zk}


#dist_dir:

zk_version: 3.4.5

dists:
  zookeeper:
    name: ${zk} 
    version: ${zk_version}
    file: ${zk}-${zk_version}.tar.gz
  
  bigtop:
    name: bigtop
    version: 0.5.0
    file: bigtop-0.5.0-project.tar.gz


zk_service: ${zk}-server

zk_install_service: true

# don't need run for deb?
zk_owned_dirs:
  - ${zk_tree.vlb}
  - ${zk_tree.log}
  - ${zk_tree.run}
  
#zk_datalog_device:
